"""create likes table

Revision ID: a9e2f1a79757
Revises: 594b23b3d23a
Create Date: 2025-01-11 01:42:42.641058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9e2f1a79757'
down_revision: Union[str, None] = '594b23b3d23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_likes',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('like', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_index(op.f('ix_movie_likes__id'), 'movie_likes', ['_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_likes__id'), table_name='movie_likes')
    op.drop_table('movie_likes')
    # ### end Alembic commands ###
